start_urls:
  - "https://www.koto-hsc.or.jp/sports_center2/introduction/"
  - "https://www.koto-hsc.or.jp/sports_center3/introduction/"
  - "https://www.koto-hsc.or.jp/sports_center4/introduction/"
  - "https://www.koto-hsc.or.jp/sports_center5/introduction/"
url_patterns:
  intro_top: "/sports_center[0-9]+/introduction/?$"
  detail_article: "/introduction/(tr_detail\\.html|post_\\d+\\.html|trainingmachine\\.html)$"
  skip:
    - "/introduction/notes\\.html$"
    - "/news/"
selectors:
  title:
    - "main h1"
    - "#main h1"
    - "h1"
  body:
    - "main"
    - "#main"
    - ".entry-content"
  address_hint:
    - "address"
    - ".info"
    - ".summary"
  equipment_blocks:
    - "table"
    - ".entry-content"
    - "main"
address_patterns:
  - "〒\\s*\\d{3}-\\d{4}[^\\n\\r<]*"
  - "東京都[^\\n]+区[^\\n]+"
keywords:
  training:
    - "トレーニング"
    - "トレーニングルーム"
    - "トレーニングマシン"
  facility:
    - "スポーツセンター"
    - "総合体育館"
