start_urls:
  - "https://www.city.sumida.lg.jp/sisetu_info/setsubi_kinou/okunaisports.html"
  - "https://www.city.sumida.lg.jp/sisetu_info/sports/umewaka.html"
  - "https://www.city.sumida.lg.jp/sisetu_info/sports/sumidasportcenter.html"
  - "https://www.city.sumida.lg.jp/sisetu_info/sports/sougou-undoujou.html"
  - "https://www.city.sumida.lg.jp/sisetu_info/tamokuteki/midori_communityc.html"
url_patterns:
  intro_top: "/sisetu_info/.+/(index\\.html|[^/]+\\.html)$"
  detail_article: "/sisetu_info/.+/(post_\\d+\\.html|detail\\.html)$"
  skip:
    - "/sisetu_info/.*/(oshirase|news)/"
selectors:
  title:
    - "main h1"
    - "#contents h1"
    - "h1"
  body:
    - "main"
    - "#contents"
    - ".entry-content"
  address_hint:
    - ".summary"
    - ".info"
    - "address"
  equipment_blocks:
    - "table"
    - ".entry-content"
    - "main"
address_patterns:
  - "〒\\s*\\d{3}-\\d{4}[^\\n\\r<]*"
  - "東京都[^\\n]+区[^\\n]+"
keywords:
  training:
    - "トレーニング"
    - "トレーニングルーム"
    - "マシン"
  facility:
    - "スポーツセンター"
    - "総合体育館"
