services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: gym_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gym_test"]
      interval: 2s
      timeout: 2s
      retries: 20

  api:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_ENV: test
      TESTING: "1"
      SENTRY_DSN: ""
      TEST_DATABASE_URL: postgresql+asyncpg://postgres:pass@db:5432/gym_test
      DATABASE_URL: postgresql+asyncpg://postgres:pass@db:5432/gym_test
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "python -c 'import sys, urllib.request; sys.exit(0 if urllib.request.urlopen(\"http://localhost:8000/readyz\").status == 200 else 1)'",
        ]
      interval: 5s
      timeout: 3s
      retries: 12
