services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${TEST_POSTGRES_DB:-gym_test}
      POSTGRES_USER: ${TEST_POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD:-postgres}
    ports:
      - "${TEST_POSTGRES_PORT:-5433}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TEST_POSTGRES_USER:-postgres} -d ${TEST_POSTGRES_DB:-gym_test}"]
      interval: 2s
      timeout: 2s
      retries: 20
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    tmpfs:
      - /var/run/postgresql
      - /tmp

volumes:
  postgres_test_data:
