[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gym-equipment-directory"
version = "0.0.1"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
include = ["app", "app.*"]