"""add parsed_json to gyms

Revision ID: 21731c9f1728
Revises: de93c8b87c0b
Create Date: 2025-12-07 17:47:56.367051

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "21731c9f1728"
down_revision: str | None = "de93c8b87c0b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gyms", sa.Column("parsed_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.alter_column(
        "gyms", "official_url", existing_type=sa.VARCHAR(), type_=sa.Text(), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "gyms", "official_url", existing_type=sa.Text(), type_=sa.VARCHAR(), existing_nullable=True
    )
    op.drop_column("gyms", "parsed_json")
    # ### end Alembic commands ###
