name: PR Preview (Single EC2)

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-1
  AMI_ID: ami-08a59875ad2a26a5f            # Amazon Linux 2023
  INSTANCE_TYPE: t3.micro
  SG_ID: sg-0600751c154b62e0c              # api-sg の ID
  SUBNET_ID: subnet-0312f79d1cf5c6bdc      # デフォルトVPCのサブネット
  KEY_NAME: ""                             # SSHしないので空にする
  INSTANCE_NAME: pr-preview
  INSTANCE_PROFILE: ec2-pr-preview-ssm
  APP_IMAGE: ghcr.io/Gosshi/gym-equipment-directory:${{ github.sha }}

jobs:
  preview:
    runs-on: ubuntu-latest
    concurrency:
      group: pr-preview-singleton
      cancel-in-progress: true

    steps:
      - name: Debug OIDC claims (aud/sub)
        uses: actions/github-script@v7
        with:
          script: |
            const id = await core.getIDToken('sts.amazonaws.com');  // aud を合わせる
            const payload = JSON.parse(Buffer.from(id.split('.')[1], 'base64').toString());
            console.log('aud:', payload.aud);
            console.log('sub:', payload.sub);
            console.log('event:', context.eventName);

      - name: Configure AWS creds (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::738755162207:role/github-oidc-pr-staging

      ## Preflight checks
      - name: "Preflight: print inputs"
        run: |
          set -x
          echo "AMI_ID=${AMI_ID}"
          echo "INSTANCE_TYPE=${INSTANCE_TYPE}"
          echo "SG_ID=${SG_ID}"
          echo "SUBNET_ID=${SUBNET_ID}"
          test -n "${{ secrets.STG_DATABASE_URL }}" || (echo "ERROR: STG_DATABASE_URL is empty" && exit 1)

      - name: "Preflight: check AMI arch & VPC/SG/Subnet"
        id: preflight
        run: |
          set -euo pipefail
          # AMI 情報
          aws ec2 describe-images --image-ids "${AMI_ID}" --query 'Images[0].{Arch:Architecture,Name:Name,Platform:PlatformDetails}' --output table
          ARCH=$(aws ec2 describe-images --image-ids "${AMI_ID}" --query 'Images[0].Architecture' --output text)
          echo "AMI_ARCH=$ARCH"
          # SG/Subnet の VPC 一致確認
          SG_VPC=$(aws ec2 describe-security-groups --group-ids "${SG_ID}" --query 'SecurityGroups[0].VpcId' --output text)
          SUBNET_VPC=$(aws ec2 describe-subnets --subnet-ids "${SUBNET_ID}" --query 'Subnets[0].VpcId' --output text)
          echo "SG_VPC=$SG_VPC SUBNET_VPC=$SUBNET_VPC"
          test "$SG_VPC" = "$SUBNET_VPC" || (echo "ERROR: SG and Subnet belong to different VPCs" && exit 1)
          # Subnet の Public IP 自動割当
          MAP_PUBLIC=$(aws ec2 describe-subnets --subnet-ids "${SUBNET_ID}" --query 'Subnets[0].MapPublicIpOnLaunch' --output text)
          echo "MapPublicIpOnLaunch=$MAP_PUBLIC"
          echo "arch=$ARCH" >> $GITHUB_OUTPUT

      - name: "Preflight: dry-run run-instances (permission check)"
        continue-on-error: true
        id: dryrun
        run: |
          set -euo pipefail
          set -x
          aws ec2 run-instances \
            --dry-run \
            --image-id "${AMI_ID}" \
            --instance-type "${INSTANCE_TYPE}" \
            --security-group-ids "${SG_ID}" \
            --subnet-id "${SUBNET_ID}" \
            --count 1 \
            2> /tmp/dryrun.err || true
          echo "----- DRY-RUN STDERR -----"
          cat /tmp/dryrun.err || true

      - name: Interpret dry-run result
        if: steps.dryrun.outcome != 'success'
        run: |
          if grep -q "DryRunOperation" /tmp/dryrun.err; then
            echo "DryRunOperation detected -> permissions OK"
            exit 0
          fi
          echo "::error::$(cat /tmp/dryrun.err)"
          exit 1
      ## End Preflight

      - name: Decide mode (upsert or destroy)
        id: mode
        run: |
          if [ "${{ github.event.action }}" = "closed" ]; then
            echo "mode=destroy-if-no-open-pr" >> "$GITHUB_OUTPUT"
          else
            echo "mode=upsert" >> "$GITHUB_OUTPUT"
          fi

      # ====== 起動/再デプロイ（opened/reopened/synchronize） ======
      - name: Upsert single preview instance
        if: steps.mode.outputs.mode == 'upsert'
        id: upsert
        shell: bash
        env:
          DATABASE_URL: ${{ secrets.STG_DATABASE_URL }}
          SENTRY_DSN: ${{ secrets.STG_SENTRY_DSN }}
        run: |
          set -Eeuo pipefail
          trap 'echo "::error::Failed at ${BASH_SOURCE}:${LINENO} — $BASH_COMMAND"' ERR
          set -x

          PR_NUM="${{ github.event.pull_request.number }}"
          NAME_TAG="${INSTANCE_NAME} (PR #${PR_NUM})"
          PURPOSE_TAG="pr-preview-singleton"

          IID=$(aws ec2 describe-instances \
            --filters "Name=tag:Purpose,Values=${PURPOSE_TAG}" \
                      "Name=instance-state-name,Values=pending,running,stopping,stopped" \
            --query 'Reservations[].Instances[].InstanceId' --output text)

          # User Data をファイルに保存
          cat > user-data.template <<'UD'
          #!/bin/bash
          set -eux
          dnf -y update
          dnf -y install docker git
          systemctl enable --now docker
          curl -sSL https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          mkdir -p /srv/app && cd /srv/app
          # Ensure APP_PORT for compose
          cat > .env <<'ENV'
          APP_PORT=8000
          ENV
          cat > docker-compose.yml <<'YML'
          services:
            api:
              image: ${APP_IMAGE}
              env_file: .env
              environment:
                APP_ENV: stg
                ALLOW_ORIGINS: "*"
                DATABASE_URL: ${DATABASE_URL}
                SENTRY_DSN: ${SENTRY_DSN}
              ports:
                - "${APP_PORT}:8000"
              command: >
                bash -lc "alembic upgrade head &&
                          uvicorn app.main:app --host 0.0.0.0 --port 8000"
          YML
          docker-compose up -d
          UD

          sed -e "s|\${APP_IMAGE}|${APP_IMAGE}|g" \
              -e "s|\${DATABASE_URL}|${DATABASE_URL}|g" \
              -e "s|\${SENTRY_DSN}|${SENTRY_DSN}|g" user-data.template > user-data.sh

          if [ -n "${IID}" ]; then
            echo "Existing instance found: ${IID}. Recreating to redeploy latest image..."
            aws ec2 terminate-instances --instance-ids "${IID}"
            aws ec2 wait instance-terminated --instance-ids "${IID}"
          fi

          IID=$(
            aws ec2 run-instances \
              --image-id "${AMI_ID}" \
              --instance-type "${INSTANCE_TYPE}" \
              --security-group-ids "${SG_ID}" \
              --subnet-id "${SUBNET_ID}" \
              --associate-public-ip-address \
              --user-data "file://$PWD/user-data.sh" \
              --count 1 \
              --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=${NAME_TAG}},{Key=Purpose,Value=${PURPOSE_TAG}},{Key=Env,Value=stg},{Key=Owner,Value=github-actions},{Key=PR,Value=${PR_NUM}}]" \
              --query 'Instances[0].InstanceId' --output text \
              --iam-instance-profile "Name=${INSTANCE_PROFILE}" 
          )
          echo "Launched instance ID: $IID"

          aws ec2 wait instance-running --instance-ids "${IID}"
          IP=$(aws ec2 describe-instances --instance-ids "${IID}" --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)
          echo "PUBLIC_IP=${IP}" >> "$GITHUB_OUTPUT"
          echo "Preview URL: http://${IP}:8000"

          echo "Waiting for TCP/8000 to be reachable..."
          for i in {1..30}; do
            if timeout 3 bash -lc "echo > /dev/tcp/${IP}/8000" 2>/dev/null; then
              echo "Port 8000 is open"
              break
            fi
            echo "  retry ${i}/30 ..."
            sleep 3
          done
          set +e
          curl -fsS "http://${IP}:8000/docs" >/dev/null || {
            curl -fsS "http://${IP}:8000/health/db" || true
            echo "::warning::App did not respond yet. Likely the container failed to start."
          }
          set -e

      - name: Check remaining open PRs
        if: steps.mode.outputs.mode == 'destroy-if-no-open-pr'
        id: remain
        uses: actions/github-script@v7
        with:
          script: |
            const prs = await github.paginate(github.rest.pulls.list, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });
            core.setOutput('open_count', prs.length);

      - name: Destroy instance if no open PRs
        if: steps.mode.outputs.mode == 'destroy-if-no-open-pr' && steps.remain.outputs.open_count == '0'
        run: |
          set -euo pipefail
          PURPOSE_TAG="pr-preview-singleton"
          IID=$(aws ec2 describe-instances \
            --filters "Name=tag:Purpose,Values=${PURPOSE_TAG}" \
                      "Name=instance-state-name,Values=pending,running,stopping,stopped" \
            --query 'Reservations[].Instances[].InstanceId' --output text)
          if [ -n "${IID}" ]; then
            aws ec2 terminate-instances --instance-ids "${IID}"
            aws ec2 wait instance-terminated --instance-ids "${IID}"
            echo "Terminated (${IID})"
          else
            echo "No instance to terminate."
          fi
