name: PR Preview (Single EC2)

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

permissions:
  id-token: write
  contents: read
  packages: write

env:
  AWS_REGION: ap-northeast-1
  AMI_ID: ami-08a59875ad2a26a5f            # Amazon Linux 2023 (x86_64)
  INSTANCE_TYPE: t3.micro
  SG_ID: sg-0600751c154b62e0c              # api-sg
  SUBNET_ID: subnet-0312f79d1cf5c6bdc      # default VPC subnet
  KEY_NAME: ""                             # SSH不要
  INSTANCE_NAME: pr-preview
  INSTANCE_PROFILE: ec2-pr-preview-ssm     # SSM用ロール（PassRole許可が必要）

jobs:
  preview:
    runs-on: ubuntu-latest
    concurrency:
      group: pr-preview-singleton
      cancel-in-progress: true

    steps:
      - name: Decide mode (upsert or destroy)
        id: mode
        run: |
          if [ "${{ github.event.action }}" = "closed" ]; then
            echo "mode=destroy-if-no-open-pr" >> "$GITHUB_OUTPUT"
          else
            echo "mode=upsert" >> "$GITHUB_OUTPUT"
          fi

      - name: Checkout
        if: steps.mode.outputs.mode == 'upsert'
        uses: actions/checkout@v4

      - name: Compute image tags (lowercase)
        if: steps.mode.outputs.mode == 'upsert'
        id: vars
        shell: bash
        run: |
          repo_lc="$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')"
          echo "REPO_LC=$repo_lc" >> "$GITHUB_OUTPUT"
          echo "APP_IMAGE=ghcr.io/$repo_lc:${GITHUB_SHA}" >> "$GITHUB_ENV"
          echo "APP_IMAGE_PR=ghcr.io/$repo_lc:pr-${{ github.event.pull_request.number }}" >> "$GITHUB_ENV"

      - name: Set up Docker Buildx
        if: steps.mode.outputs.mode == 'upsert'
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        if: steps.mode.outputs.mode == 'upsert'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        if: steps.mode.outputs.mode == 'upsert' && github.event.pull_request.head.repo.fork == false
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.APP_IMAGE }}
            ${{ env.APP_IMAGE_PR }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Configure AWS creds (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::738755162207:role/github-oidc-pr-staging

      - name: Upsert single preview instance
        if: steps.mode.outputs.mode == 'upsert'
        id: upsert
        shell: bash
        env:
          DATABASE_URL: ${{ secrets.STG_DATABASE_URL }}
          SENTRY_DSN: ${{ secrets.STG_SENTRY_DSN }}
          GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          set -Eeuo pipefail
          trap 'echo "::error::Failed at ${BASH_SOURCE}:${LINENO} — $BASH_COMMAND"' ERR

          PR_NUM="${{ github.event.pull_request.number }}"
          NAME_TAG="${INSTANCE_NAME}-pr${PR_NUM}"
          PURPOSE_TAG="pr-preview-singleton"

          cat > user-data.template <<'UD'
          #!/bin/bash
          set -eux
          dnf -y update
          dnf -y install docker git
          systemctl enable --now docker

          usermod -aG docker ec2-user || true
          usermod -aG docker ssm-user || true
          for i in {1..30}; do [ -S /var/run/docker.sock ] && break || sleep 1; done
          chmod 666 /var/run/docker.sock || true

          mkdir -p /usr/local/lib/docker/cli-plugins
          curl -fL -o /usr/local/lib/docker/cli-plugins/docker-compose \
            https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-linux-x86_64
          chmod +x /usr/local/lib/docker/cli-plugins/docker-compose

          mkdir -p /srv/app && cd /srv/app

          # GHCR login (必須)
          if [ -z "${GHCR_TOKEN:-}" ] || [ -z "${GHCR_USERNAME:-}" ]; then
            echo "ERROR: GHCR credentials not provided"; exit 1
          fi
          echo "${GHCR_TOKEN}" | docker login ghcr.io -u "${GHCR_USERNAME}" --password-stdin

          cat > .env <<'ENV'
          APP_PORT=8000
          ENV

          cat > docker-compose.yml <<'YML'
          services:
            api:
              image: ${APP_IMAGE}
              env_file: .env
              environment:
                APP_ENV: stg
                ALLOW_ORIGINS: "*"
                DATABASE_URL: ${DATABASE_URL}
                SENTRY_DSN: ${SENTRY_DSN}
              ports:
                - "${APP_PORT}:8000"
              command: >
                bash -lc "alembic upgrade head &&
                          uvicorn app.main:app --host 0.0.0.0 --port 8000"
          YML

          # Pull image (retry)
          for i in {1..5}; do
            docker pull "${APP_IMAGE}" && break
            echo "pull retry $i"; sleep 5
          done
          docker image inspect "${APP_IMAGE}" >/dev/null 2>&1 || { echo "ERROR: docker pull failed"; exit 1; }

          docker compose up -d
          UD

          # sed substitution
          safe() { printf '%s' "$1" | sed -e 's/[&]/\\&/g'; }
          sed -e "s|\${APP_IMAGE}|$(safe "${APP_IMAGE}")|g" \
              -e "s|\${DATABASE_URL}|$(safe "${DATABASE_URL}")|g" \
              -e "s|\${SENTRY_DSN}|$(safe "${SENTRY_DSN}")|g" \
              -e "s|\${GHCR_USERNAME}|$(safe "${GHCR_USERNAME}")|g" \
              -e "s|\${GHCR_TOKEN}|$(safe "${GHCR_TOKEN}")|g" \
              -e "s|\${GHCR_AUTH_B64}|$(printf '%s' "${GHCR_USERNAME}:${GHCR_TOKEN}" | base64 -w0)|g" \
              user-data.template > user-data.sh

          aws ec2 run-instances \
            --image-id "${AMI_ID}" \
            --instance-type "${INSTANCE_TYPE}" \
            --security-group-ids "${SG_ID}" \
            --subnet-id "${SUBNET_ID}" \
            --associate-public-ip-address \
            --user-data "file://$PWD/user-data.sh" \
            --count 1 \
            --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=${NAME_TAG}},{Key=Purpose,Value=${PURPOSE_TAG}},{Key=Env,Value=stg},{Key=Owner,Value=github-actions},{Key=PR,Value=${PR_NUM}}]" \
            --query 'Instances[0].InstanceId' \
            --output text \
            --iam-instance-profile "Name=${INSTANCE_PROFILE}"