name: test
on: [push, pull_request]
jobs:
  unit:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: gym_test
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d gym_test"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: python -m pip install -U pip && pip install -r requirements.txt
      - name: run tests
        env:
          TEST_DATABASE_URL: postgresql+asyncpg://postgres:pass@localhost:5433/gym_test
        run: pytest -q
